export const ROUTE_PATH = {
  root: '/',
  index: '/users',
  signIn: '/signin',
  signUp: '/signup',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  verifyEmail: '/verify-email',
  users: '/users',
  profile: '/profile',
  tasks: '/tasks',
  files: '/files',
  tenants: '/tenants',
  dashboard: '/dashboard',
  auditLogs: '/audit-logs',
  mailTemplates: '/mail-templates',
  notFound: '/404',
} as const;
